# Generated by Django 5.1.6 on 2025-03-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_domain_rename_domain_group_apikey_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='next_subscription_renewal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='pwn_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='pwn_count_excluding_spam_lists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='pwn_count_excluding_spam_lists_at_last_subscription_renewal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
