# Generated by Django 5.1.6 on 2025-03-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_domain_next_subscription_renewal_domain_pwn_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HIBPKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional label or notes for this key.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
