# Dockerfile.prod
FROM dtuait/pwned-proxy-app-main:python-3.13-bullseye-django-5.1.6-myversion-1.0.2

# Copy project source into the image
COPY . /usr/src/project
WORKDIR /usr/src/project/app-main   # this folder HAS manage.py now

# Copy entrypoint script and run it at container start
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Start the Django app via the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]

